--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    id integer NOT NULL,
    type smallint DEFAULT 2 NOT NULL,
    nombre text NOT NULL,
    correo text NOT NULL,
    "contraseña" text NOT NULL,
    fecha_registro time without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historystate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historystate (
    id integer NOT NULL,
    tramite_id integer NOT NULL,
    estado_anterior text,
    estado_nuevo text,
    fecha_cambio timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usuario_id integer NOT NULL
);


ALTER TABLE public.historystate OWNER TO postgres;

--
-- Name: historystate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.historystate_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.historystate_id_seq OWNER TO postgres;

--
-- Name: historystate_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.historystate_id_seq OWNED BY public.historystate.id;


--
-- Name: tramites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tramites (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    tipo text NOT NULL,
    descripcion text,
    estado text DEFAULT 'Recibido'::text NOT NULL,
    archivo_adjuntado text NOT NULL,
    fecha_solicitud timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    nombre text NOT NULL,
    fecha_nacimiento date NOT NULL,
    lugar_nacimiento text NOT NULL,
    nombre_padre text NOT NULL,
    nombre_madre text NOT NULL,
    genero text NOT NULL,
    descargado character varying(10) DEFAULT 'No'::character varying NOT NULL
);


ALTER TABLE public.tramites OWNER TO postgres;

--
-- Name: tramites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tramites_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tramites_id_seq OWNER TO postgres;

--
-- Name: tramites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tramites_id_seq OWNED BY public.tramites.id;


--
-- Name: historystate id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historystate ALTER COLUMN id SET DEFAULT nextval('public.historystate_id_seq'::regclass);


--
-- Name: tramites id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tramites ALTER COLUMN id SET DEFAULT nextval('public.tramites_id_seq'::regclass);


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" (id, type, nombre, correo, "contraseña", fecha_registro) FROM stdin;
12	2	Jose Guillermo	jg387782@gmail.com	$2a$06$pnqgAM5UkIyO7qoF6V1i/OcBzUL3NgBjoiQTjNZF.15yY8hJt4NMK	23:26:30.890235
13	1	Admin	admin@root.com	$2a$06$BrdnMXQjjscnbdAf/9M/reslWPbth2cDPyB6s22TFfSD2cO7VG7Om	00:03:40.209074
\.


--
-- Data for Name: historystate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.historystate (id, tramite_id, estado_anterior, estado_nuevo, fecha_cambio, usuario_id) FROM stdin;
\.


--
-- Data for Name: tramites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tramites (id, usuario_id, tipo, descripcion, estado, archivo_adjuntado, fecha_solicitud, fecha_actualizacion, nombre, fecha_nacimiento, lugar_nacimiento, nombre_padre, nombre_madre, genero, descargado) FROM stdin;
11	12	2	\N	Emitido	1753936892628-992883977.pdf	2025-07-31 00:00:00	2025-07-30 23:41:32.667778	Jose Guillermo Gutierrez Sanchez	2001-01-15	Chiriquí	Enatalio Gutierrez	Eneida Sanchez	Masculino	Si
\.


--
-- Name: Users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_id_seq"', 13, true);


--
-- Name: historystate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historystate_id_seq', 1, false);


--
-- Name: tramites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tramites_id_seq', 11, true);


--
-- Name: Users UNIQUE; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "UNIQUE" UNIQUE (correo);


--
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- Name: historystate historystate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historystate
    ADD CONSTRAINT historystate_pkey PRIMARY KEY (id);


--
-- Name: tramites tramites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tramites
    ADD CONSTRAINT tramites_pkey PRIMARY KEY (id);


--
-- Name: historystate historystate_tramite_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historystate
    ADD CONSTRAINT historystate_tramite_id_fkey FOREIGN KEY (tramite_id) REFERENCES public.tramites(id);


--
-- Name: historystate historystate_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historystate
    ADD CONSTRAINT historystate_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public."Users"(id);


--
-- Name: tramites tramites_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tramites
    ADD CONSTRAINT tramites_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public."Users"(id);


--
-- PostgreSQL database dump complete
--

